apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: audit
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - kyverno-test
      verifyImages:
      - imageReferences:
        - "index.docker.io/sagarkundral/test-signed-image:*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEswfro84NoeTms9TQl0q4ML6/21RM
                CVgL1Rue3A3U1x6G8aJny5p3Tjc+ZS06KuD+VKz5jgtIZxoqBNyMATyOmQ==
                -----END PUBLIC KEY-----
